### PR TITLE
[Fix]Rehash gpu table before importing values and reduce size kernel call.

### PR DESCRIPTION
**Pull request by acmore**
# Description

This PR is to fix gpu table import issues. It will expand the table to appropriate size before importing values. And it will try to minimize the number of calls to size kernel.

## Type of change

- [x] Bug fix
- [ ] New Tutorial
- [ ] Updated or additional documentation
- [ ] Additional Testing
- [ ] New Feature

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/recommenders-addons/blob/master/CONTRIBUTING.md#coding-style)
    - [x] By running yapf
    - [x] By running clang-format
- [ ] This PR addresses an already submitted issue for TensorFlow Recommenders-Addons
- [ ] I have made corresponding changes to the documentation
- [x] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?

If you're adding a bugfix or new feature please describe the tests that you ran to verify your changes:
*

### CODE REVIEW

**Comment by acmore** [comment]
temporary closed to test more cases.

**Comment by rhdong** [comment]
Hi @acmore , sorry for lately replying, we should discuss on the PR and help to merge it ASAP. Could you send your WeChat account to my mail(rhdong2017@gmail.com)? Thank you!

**Comment by acmore** [comment]
> 

HI @rhdong sent

**Comment by rhdong** [comment]
Hi @acmore, this PR is LGTM. Before merging it, please squash all of the commits into one and resolve the conflicts and clang check failure, thank you!

**Comment by acmore** [comment]
Hi @rhdong I updated the mr, but I am not sure how to do squash properly. Maybe you could select Squash and merge commit option when you merge this mr? Thanks

**Pull request merged**
