### PR TITLE
[CI] Add .bazelversion file

### PR DESCRIPTION
**Pull request by fuhailin**
# Description
Specify an accurate bazel version for building.

Brief Description of the PR:

Fixes # (issue)

## Type of change

- [ ] Bug fix
- [ ] New Tutorial
- [ ] Updated or additional documentation
- [ ] Additional Testing
- [x] New Feature

# Checklist:

- [ ] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/recommenders-addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running yapf
    - [ ] By running clang-format
- [ ] This PR addresses an already submitted issue for TensorFlow Recommenders-Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?

If you're adding a bugfix or new feature please describe the tests that you ran to verify your changes:
*

### CODE REVIEW

**Comment by rhdong** [comment]
> Thanks for your pull request! It looks like this may be your first contribution to a Google open source project. Before we can look at your pull request, you'll need to sign a Contributor License Agreement (CLA).
> 
> View this [failed invocation](https://github.com/tensorflow/recommenders-addons/pull/348/checks?check_run_id=15102735176) of the CLA check for more information.
> 
> For the most up to date status, view the checks section at the bottom of the pull request.

Hi @fuhailin, thank you for your contribution, and per the notice above, it possible you need to sign the CLA by following the [guidance](https://github.com/tensorflow/recommenders-addons/pull/348/checks?check_run_id=15102735176).

**Comment by fuhailin** [comment]
Hi @rhdong I have already signed the CLA, please view the latest [link](https://github.com/tensorflow/recommenders-addons/pull/348/checks?check_run_id=15165383719)

**Comment by rhdong** [comment]
Hi @fuhailin , would you please squash the three small commits into one? thank you!

**Comment by fuhailin** [comment]
I open a new branch for this PR, please check https://github.com/tensorflow/recommenders-addons/pull/355

**Pull request closed without merging**
