### PR TITLE
[fix] embedding variable graph mode example 

### PR DESCRIPTION
**Pull request by Nov11**
# Description

Brief Description of the PR:
fix embedding variable graph mode example in jupyter notebook under docs/tutorial

Fixes # (issue)

## Type of change

- [ ] Bug fix
- [ ] New Tutorial
- [x] Updated or additional documentation
- [ ] Additional Testing
- [ ] New Feature

# Checklist:

- [x] I've properly [formatted my code according to the guidelines](https://github.com/tensorflow/recommenders-addons/blob/master/CONTRIBUTING.md#coding-style)
    - [ ] By running yapf
    - [ ] By running clang-format
- [ ] This PR addresses an already submitted issue for TensorFlow Recommenders-Addons
- [ ] I have made corresponding changes to the documentation
- [ ] I have added tests that prove my fix is effective or that my feature works

# How Has This Been Tested?

rerun the notebook and it shows output as expected

If you're adding a bugfix or new feature please describe the tests that you ran to verify your changes:
*

### CODE REVIEW

**Comment by rhdong** [comment]
Hi @liutongxuan @qqsun8819 ,please help review this PR, thanks!

**Review by qqsun8819 — APPROVED** [review]

**Review by liutongxuan — APPROVED** [review]

**Comment by rhdong** [comment]
Hi @Nov11 , please rebase on origin/master and squash all commits to one, after this, I'll merge it, thank you!

**Comment by Nov11** [comment]
> Hi @Nov11 , please rebase on origin/master and squash all commits to one, after this, I'll merge it, thank you!

Branch has been rebased on master. Please check this PR again.

**Comment by rhdong** [comment]
> > Hi @Nov11 , please rebase on origin/master and squash all commits to one, after this, I'll merge it, thank you!
> 
> Branch has been rebased on master. Please check this PR again.

Done, thank you for your contribution!

**Pull request merged**
